version: '3.8'

# NAS 多租户部署配置
# 每个项目使用独立的容器，数据存储在 NAS 上
# 使用上游开源主线代码，支持多项目模式

services:
  # 项目 001
  project-001:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claude-project-001
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET:-change-me-in-production}
    volumes:
      # Claude 会话数据挂载
      - /nas/claude/001:/opt/claude-config
      # SSH 密钥（只读）
      - ~/.ssh:/home/claudeuser/.ssh:ro
      # Git 配置（只读）
      - ~/.gitconfig:/home/claudeuser/.gitconfig:ro
    restart: unless-stopped
    networks:
      - claude-network

  # 项目 002（按需添加更多项目）
  project-002:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claude-project-002
    ports:
      - "3002:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET:-change-me-in-production}
    volumes:
      - /nas/claude/002:/opt/claude-config
      - ~/.ssh:/home/claudeuser/.ssh:ro
      - ~/.gitconfig:/home/claudeuser/.gitconfig:ro
    restart: unless-stopped
    networks:
      - claude-network

networks:
  claude-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# 使用说明：
# 1. 确保 NAS 目录存在：/nas/claude/001/、/nas/claude/002/ 等
# 2. 启动所有项目：docker-compose -f docker-compose.nas.yml up -d
# 3. 启动特定项目：docker-compose -f docker-compose.nas.yml up -d project-001
# 4. 查看日志：docker-compose -f docker-compose.nas.yml logs -f project-001
# 5. Claude CLI 会自动在 /opt/claude-config/.claude/projects/ 下创建项目
