import type { Observable } from "rxjs";
import type {
  AnyMessage,
  ContentBlock,
  SessionState,
  SessionMetadata,
  TokenUsage,
} from "@deepractice-ai/agent-types";
import type { AgentAdapter } from "./adapter";
import type { MessagePersister } from "./persister";
import type { SessionOptions } from "./config";

/**
 * Session interface - SDK-specific with Observable methods
 * This is different from agent-types Session which is a data structure
 */
export interface Session {
  readonly id: string;
  readonly createdAt: Date;
  readonly state: SessionState;

  // Actions
  send(content: string | ContentBlock[]): Promise<void>;
  abort(): Promise<void>;
  complete(): Promise<void>;
  delete(): Promise<void>;

  // Observables
  messages$(): Observable<AnyMessage>;

  // Queries
  getMessages(limit?: number, offset?: number): AnyMessage[];
  getTokenUsage(): TokenUsage;
  getMetadata(): SessionMetadata;
  summary(): string;

  // Utilities
  isActive(): boolean;
  isCompleted(): boolean;
}

/**
 * Options for creating a new session
 */
export interface SessionCreateOptions {
  model?: string;
  initialMessage: string; // Required: lazy session creation
}

/**
 * Session Factory interface
 * Responsible for creating Session instances
 *
 * Different AI providers may have different Session implementations
 * (e.g., ClaudeSession, OpenAISession), factory pattern decouples
 * the creation logic from the core Agent/SessionManager
 */
export interface SessionFactory {
  /**
   * Create a new session instance
   *
   * @param id - Session ID (generated by caller)
   * @param metadata - Session metadata
   * @param adapter - AI adapter for this session
   * @param options - Session options
   * @param persister - Optional message persister
   * @returns Session instance
   */
  createSession(
    id: string,
    metadata: SessionMetadata,
    adapter: AgentAdapter,
    options: SessionOptions,
    persister?: MessagePersister
  ): Session;
}
